# Pandas 데이터 불러오기 연습

In [58]:
import os
import pandas as pd

### C:\Python_VSCode_Cursor\XAU_1d_data.csv 경로에 있는 모든 파일

In [59]:
os.listdir(r"C:\Python_VSCode_Cursor")

['.git',
 '.vscode',
 'ClickMacro.py',
 'ML_Gold_Price.py',
 'SnakeGame.py',
 'WebScraping_practice',
 'XAU_1d_data.csv',
 '거친코딩머신러닝',
 '나도코딩머신러닝']

### pandas 라이브러리를 이용해 파일 읽기(csv 파일)

In [60]:
df = pd.read_csv("C:\Python_VSCode_Cursor/XAU_1d_data.csv", encoding="utf8")
df.head(5) # 5개만 읽기

         Date   Open   High    Low  Close  Volume
0  2004.06.11  384.0  384.8  382.8  384.1     272
1  2004.06.14  384.3  385.8  381.8  382.8    1902
2  2004.06.15  382.8  388.8  381.1  388.6    1951
3  2004.06.16  387.1  389.8  382.6  383.8    2014
4  2004.06.17  383.6  389.3  383.0  387.6    1568

### 파일 저장하기

In [61]:
df.to_csv("C:\Python_VSCode_Cursor\XAU_1d_data.csv", 
          index=False, 
          encoding="utf8")

In [62]:
pd.read_csv("C:\Python_VSCode_Cursor\XAU_1d_data.csv")

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     272
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]

In [63]:
os.listdir("C:\Python_VSCode_Cursor")

['.git',
 '.vscode',
 'ClickMacro.py',
 'ML_Gold_Price.py',
 'SnakeGame.py',
 'WebScraping_practice',
 'XAU_1d_data.csv',
 '거친코딩머신러닝',
 '나도코딩머신러닝']

# Series 연습

In [64]:
import numpy as np

### Series()와 np.array()의 차이

In [65]:
print(pd.Series([1,2,3]))
np.array([1,2,3])

0    1
1    2
2    3
dtype: int64

array([1, 2, 3])

### 데이터프레임에서 컬럼명을 사용해 시리즈 생성

In [66]:
series = df["Open"]
series

0        384.00
1        384.30
2        382.80
3        387.10
4        383.60
         ...
5386    3298.76
5387    3383.51
5388    3353.93
5389    3373.34
5390    3353.55
Name: Open, Length: 5391, dtype: float64

### 시리즈 생성(index, dtype 지정) dtype = 데이터의 타입 ex)float, int

In [67]:
series = pd.Series(
                    [1,2,3,4,5],
                    index=["a","b","c","d","e"],
                    dtype=float
)
series

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

### series 정렬하기

In [68]:
series = pd.Series(
                    [10,3,2,6,5],
                    index=["a","b","c","d","e"],
                    dtype=float
)
print(series.sort_values(ascending=True)) # 오름차순(생략가능)
print(series.sort_values(ascending=False)) # 내림차순

c     2.0
b     3.0
e     5.0
d     6.0
a    10.0
dtype: float64
a    10.0
d     6.0
e     5.0
b     3.0
c     2.0
dtype: float64

# DataFrame 연습

### Dictionary 형태로 데이터프레임 생성(키:컬럼 , 값:데이터값)

In [69]:
df = pd.DataFrame({"이도":["잘생김","천재"],"누나":["못생김","바보"]})
df

    이도   누나
0  잘생김  못생김
1   천재   바보

### List 형태로 데이터프레임 생성
### (컬럼 따로 지정, 리스트 값들이 row로 저장)

In [70]:
df = pd.DataFrame([[2,10,20],[3,15,45],[6,7,42]],
                  columns=["a","b","c"],
                  index=["가","나","다"],
                  dtype=float)
df

     a     b     c
가  2.0  10.0  20.0
나  3.0  15.0  45.0
다  6.0   7.0  42.0

# DataFrame 행, 열, 선택 및 필터링

In [71]:
df = pd.read_csv("C:\Python_VSCode_Cursor\XAU_1d_data.csv", encoding="utf-8")
df

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     272
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]

### index 3625번에 해당하는 row 가져오기

In [72]:
df.iloc[3625] # type = series

Date      2018.08.03
Open         1208.68
High         1219.98
Low           1204.4
Close        1213.14
Volume         97927
Name: 3625, dtype: object

In [73]:
df.iloc[[3625]] # type = DataFrame

            Date     Open     High     Low    Close  Volume
3625  2018.08.03  1208.68  1219.98  1204.4  1213.14   97927

### 컬럼 가져오기

In [74]:
df["Open"] # 컬럼 Open 가져오기

0        384.00
1        384.30
2        382.80
3        387.10
4        383.60
         ...
5386    3298.76
5387    3383.51
5388    3353.93
5389    3373.34
5390    3353.55
Name: Open, Length: 5391, dtype: float64

In [75]:
df.loc[:,"Open"]

0        384.00
1        384.30
2        382.80
3        387.10
4        383.60
         ...
5386    3298.76
5387    3383.51
5388    3353.93
5389    3373.34
5390    3353.55
Name: Open, Length: 5391, dtype: float64

In [76]:
df.loc[3625,"Open"]

np.float64(1208.68)

In [77]:
df.iloc[3625,1]

np.float64(1208.68)

In [78]:
df.drop(["Open"], axis=1)

            Date     High      Low    Close  Volume
0     2004.06.11   384.80   382.80   384.10     272
1     2004.06.14   385.80   381.80   382.80    1902
2     2004.06.15   388.80   381.10   388.60    1951
3     2004.06.16   389.80   382.60   383.80    2014
4     2004.06.17   389.30   383.00   387.60    1568
...          ...      ...      ...      ...     ...
5386  2025.06.02  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3369.26  3353.00  3368.94  120857

[5391 rows x 5 columns]

In [79]:
df

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     272
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]

# 데이터프레임 삭제

In [80]:
df.drop(list(range(0,200,2)),axis=0).head(200)

           Date   Open   High    Low  Close  Volume
1    2004.06.14  384.3  385.8  381.8  382.8    1902
3    2004.06.16  387.1  389.8  382.6  383.8    2014
5    2004.06.18  388.6  395.8  385.8  394.3    2257
7    2004.06.22  392.8  396.3  392.3  394.1    1407
9    2004.06.24  394.0  402.8  393.1  401.1    1991
..          ...    ...    ...    ...    ...     ...
295  2005.08.11  437.0  446.8  436.8  445.3    1103
296  2005.08.12  446.0  449.1  443.5  445.7     934
297  2005.08.15  445.7  445.7  440.8  442.3     661
298  2005.08.16  441.8  446.5  440.0  445.8     934
299  2005.08.17  445.3  445.7  437.8  440.3    1022

[200 rows x 6 columns]

In [81]:
df

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     272
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]

# 데이터프레임 수정

In [84]:
df.loc[0,"Volume"] = 270
df

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     270
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]

In [86]:
df.iloc[0,5] = 272
df

            Date     Open     High      Low    Close  Volume
0     2004.06.11   384.00   384.80   382.80   384.10     272
1     2004.06.14   384.30   385.80   381.80   382.80    1902
2     2004.06.15   382.80   388.80   381.10   388.60    1951
3     2004.06.16   387.10   389.80   382.60   383.80    2014
4     2004.06.17   383.60   389.30   383.00   387.60    1568
...          ...      ...      ...      ...      ...     ...
5386  2025.06.02  3298.76  3382.86  3295.75  3380.64  461738
5387  2025.06.03  3383.51  3392.19  3333.08  3352.91  436080
5388  2025.06.04  3353.93  3384.64  3343.67  3372.25  420245
5389  2025.06.05  3373.34  3403.42  3339.43  3351.98  808095
5390  2025.06.06  3353.55  3369.26  3353.00  3368.94  120857

[5391 rows x 6 columns]