# apply() 함수 연습

In [1]:
import pandas as pd
import os
import numpy as np

In [3]:
abalone_df = pd.read_csv(r"C:\Python_VSCode_Cursor\거친코딩머신러닝\abalone.data", header=None, sep=",",
                         names=['sex','length','diameter','height', 
                                'whole_weight','shucked_weight','viscera_weight', 
                                'shell_weight','rings'])
abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [ ]:
abalone_df[["diameter"]].apply(np.average, axis=0) # 세로방향으로 np.average 적용

diameter    0.407881
dtype: float64

In [9]:
abalone_df[["diameter"]].apply(np.average, axis=1) # 가로방향으로 np.average 적용

0       0.365
1       0.265
2       0.420
3       0.365
4       0.255
        ...
4172    0.450
4173    0.440
4174    0.475
4175    0.485
4176    0.555
Length: 4177, dtype: float64

# 사용자 함수를 이용한 집계 (중요!!)

In [ ]:
import math

In [18]:
def average_round(list):
    return round((sum(list))/(len(list)),2)

In [19]:
abalone_df[["diameter", "height", "whole_weight"]].apply(lambda x : average_round(x), axis=1)

0       0.32
1       0.19
2       0.41
3       0.34
4       0.18
        ...
4172    0.50
4173    0.51
4174    0.62
4175    0.58
4176    0.90
Length: 4177, dtype: float64

In [38]:
def Q1(x,y,z):
    global answer
    if x + y + z >= 1 : 
        answer = True
        return(answer)
    else:
        answer = False
        return(answer)
    
abalone_df_copy = abalone_df.copy()
answer = abalone_df[["diameter","height","whole_weight"]] \
    .apply(lambda x: Q1(x.iloc[0],x.iloc[1],x.iloc[2]), axis=1)
abalone_df_copy["answer"] = answer
abalone_df_copy

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings,answer
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,False
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,False
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,True
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,True
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,False
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,True
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,True
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,True
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,True
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,True

In [42]:
sum(answer)

2914

# DataFrame 합치기

In [49]:
one_abalone = abalone_df.iloc[[0]]
one_abalone

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15

In [51]:
pd.concat([abalone_df, one_abalone], axis=0)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15

In [61]:
one_abalone = abalone_df.iloc[:,0]
one_abalone

0       M
1       M
2       F
3       M
4       I
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: sex, Length: 4177, dtype: object

In [62]:
pd.concat([abalone_df,one_abalone], axis=1)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings,sex
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15,M
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7,M
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9,F
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10,M
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7,I
...,...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11,F
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10,M
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9,M
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10,F
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12,M