# Groupby 연습

In [59]:
import os
import pandas as pd
import numpy as np

In [3]:
os.listdir("C:/Python_VSCode_Cursor/거친코딩머신러닝/")

['abalone.data',
 'Example.csv',
 'Example_csv_maker.ipynb',
 'Pandas_practice.ipynb',
 'Pandas_practice_groupby.ipynb',
 'Pandas_practice_review.ipynb']

In [6]:
abalone_src = "C:/Python_VSCode_Cursor/거친코딩머신러닝/abalone.data"

abalone_df = pd.read_csv(abalone_src, header=None, sep=",",
                         names=['sex','length','diameter','height', 
                                'whole_weight','shucked_weight','viscera_weight', 
                                'shell_weight','rings'])

abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

### 데이터가 비어있는지 확인

In [7]:
abalone_df.isnull()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4172,False,False,False,False,False,False,False,False,False
4173,False,False,False,False,False,False,False,False,False
4174,False,False,False,False,False,False,False,False,False
4175,False,False,False,False,False,False,False,False,False
4176,False,False,False,False,False,False,False,False,False

In [8]:
abalone_df.isnull().sum() # True = 1, False = 0

sex               0
length            0
diameter          0
height            0
whole_weight      0
shucked_weight    0
viscera_weight    0
shell_weight      0
rings             0
dtype: int64

In [9]:
abalone_df.isnull().sum().sum()

np.int64(0)

### 기술통계 확인

In [10]:
abalone_df.describe()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

### groupby

In [17]:
grouped = abalone_df["whole_weight"].groupby(abalone_df["sex"])
# 성별을 기준으로 전복의 무게를 집계
grouped.describe()

      count      mean       std     min       25%      50%       75%     max
sex
F    1307.0  1.046532  0.430316  0.0800  0.730000  1.03850  1.320250  2.6570
I    1342.0  0.431363  0.286275  0.0020  0.205500  0.38400  0.599375  2.0495
M    1528.0  0.991459  0.470581  0.0155  0.671625  0.97575  1.265625  2.8255

In [22]:
abalone_df.groupby(abalone_df["sex"]).mean()

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
sex,,,,,,,,
F,0.579093,0.454732,0.158011,1.046532,0.446188,0.230689,0.302010,11.129304
I,0.427746,0.326494,0.107996,0.431363,0.191035,0.092010,0.128182,7.890462
M,0.561391,0.439287,0.151381,0.991459,0.432946,0.215545,0.281969,10.705497

In [23]:
abalone_df.groupby("sex").mean() # 위 코드와 같은 역할 수행

,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
sex,,,,,,,,
F,0.579093,0.454732,0.158011,1.046532,0.446188,0.230689,0.302010,11.129304
I,0.427746,0.326494,0.107996,0.431363,0.191035,0.092010,0.128182,7.890462
M,0.561391,0.439287,0.151381,0.991459,0.432946,0.215545,0.281969,10.705497

### 중복 데이터 삭제

In [26]:
abalone_df.duplicated().sum() # 중복된 데이터가 존재하지 않음

np.int64(0)

In [29]:
duplicate_abalone = abalone_df.iloc[[0]] # 중복된 조개 데이터 생성
duplicate_abalone

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15

In [36]:
duplicate_abalone_df = pd.concat([abalone_df,duplicate_abalone], axis=0)
duplicate_abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15

In [34]:
duplicate_abalone_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4173    False
4174    False
4175    False
4176    False
0        True
Length: 4178, dtype: bool

In [35]:
duplicate_abalone_df.duplicated().sum()

np.int64(1)

### 중복 데이터 삭제

In [39]:
duplicate_abalone_df.drop_duplicates(inplace=True)
duplicate_abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [43]:
(duplicate_abalone_df == abalone_df).sum() # 중복을 없앤 중복 생성 데이터와 원래 데이터가 같은지 확인

sex               4177
length            4177
diameter          4177
height            4177
whole_weight      4177
shucked_weight    4177
viscera_weight    4177
shell_weight      4177
rings             4177
dtype: int64

# 빈 데이터 삭제 (Nan)

In [47]:
NaN_abalone_df = abalone_df.copy()

NaN_abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [48]:
NaN_abalone_df.iloc[0,1] = np.nan
NaN_abalone_df

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,NaN,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [54]:
NaN_abalone_df.isnull().sum().sum()

np.int64(1)

In [61]:
NaN_abalone_df.mean(numeric_only=True)

length            0.524009
diameter          0.407881
height            0.139516
whole_weight      0.828742
shucked_weight    0.359367
viscera_weight    0.180594
shell_weight      0.238831
rings             9.933684
dtype: float64

In [63]:
NaN_abalone_df.fillna(NaN_abalone_df.mean(numeric_only=True))

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.524009,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350000,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530000,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440000,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330000,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565000,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590000,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600000,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625000,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710000,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12