# **Pandas** 라이브러리 복습

#

### 모듈 불러오기

In [18]:
import os
import pandas as pd

In [19]:
os.listdir("C:/Python_VSCode_Cursor/") # 데이터 불러오기

['.git',
 '.vscode',
 'ClickMacro.py',
 'ML_Gold_Price.py',
 'SnakeGame.py',
 'WebScraping_practice',
 'XAU_1d_data.csv',
 '거친코딩머신러닝',
 '나도코딩머신러닝']

In [65]:
df = pd.read_csv("C:\Python_VSCode_Cursor\거친코딩머신러닝\Example.csv") # 금 가격 csv 파일 불러오기
df

      x    x^2      x^3
0     1      1        1
1     2      4        8
2     3      9       27
3     4     16       64
4     5     25      125
..  ...    ...      ...
95   96   9216   884736
96   97   9409   912673
97   98   9604   941192
98   99   9801   970299
99  100  10000  1000000

[100 rows x 3 columns]

In [ ]:
df.iloc[93,2]

np.int64(8836)

In [30]:
df.loc[93,"x^3"]

np.int64(830584)

In [35]:
df.loc[:,"x^2"]

0         1
1         4
2         9
3        16
4        25
      ...
95     9216
96     9409
97     9604
98     9801
99    10000
Name: x^2, Length: 100, dtype: int64

In [37]:
df.iloc[90:100,:]

      x    x^2      x^3
90   91   8281   753571
91   92   8464   778688
92   93   8649   804357
93   94   8836   830584
94   95   9025   857375
95   96   9216   884736
96   97   9409   912673
97   98   9604   941192
98   99   9801   970299
99  100  10000  1000000

# 조건 필터링

### *int,float*

In [44]:
df[df["x^2"] >= 1000] # x^2가 1000보다 큰 것 출력

      x    x^2      x^3
31   32   1024    32768
32   33   1089    35937
33   34   1156    39304
34   35   1225    42875
35   36   1296    46656
..  ...    ...      ...
95   96   9216   884736
96   97   9409   912673
97   98   9604   941192
98   99   9801   970299
99  100  10000  1000000

[69 rows x 3 columns]

### *str*

In [46]:
df1 = pd.DataFrame({"name":["이도","이연","동희","윤하"],"age":[13,13,47,44]})
df1

  name  age
0   이도   13
1   이연   13
2   동희   47
3   윤하   44

In [47]:
df1.name == "이도"

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [48]:
df1[df1.name == "이도"]

  name  age
0   이도   13

### *조건 여러개*

#### and function

In [52]:
df[(df["x^2"] >= 1000) & (df["x^2"] <= 2000)] # 괄호로 조건을 묶기

     x   x^2    x^3
31  32  1024  32768
32  33  1089  35937
33  34  1156  39304
34  35  1225  42875
35  36  1296  46656
36  37  1369  50653
37  38  1444  54872
38  39  1521  59319
39  40  1600  64000
40  41  1681  68921
41  42  1764  74088
42  43  1849  79507
43  44  1936  85184

#### or function

In [55]:
df[(df["x^2"] <= 100) | (df["x^2"] >= 9000)] # 괄호로 조건을 묶기

      x    x^2      x^3
0     1      1        1
1     2      4        8
2     3      9       27
3     4     16       64
4     5     25      125
5     6     36      216
6     7     49      343
7     8     64      512
8     9     81      729
9    10    100     1000
94   95   9025   857375
95   96   9216   884736
96   97   9409   912673
97   98   9604   941192
98   99   9801   970299
99  100  10000  1000000

In [66]:
import numpy as np
df = pd.DataFrame(np.arange(12).reshape(3,4), 
                  columns=["A","B","C","D"])
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

# 데이터 삭제

In [62]:
df.drop(["B","C"], axis=1)

   A   D
0  0   3
1  4   7
2  8  11

In [64]:
df.drop([1], axis=0)

   A  B   C   D
0  0  1   2   3
2  8  9  10  11

# 데이터 수정

In [67]:
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [70]:
df.loc[1,"B"] = "오"
df

   A  B   C   D
0  0  1   2   3
1  4  오   6   7
2  8  9  10  11

In [72]:
df.iloc[1,1] = 5
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [73]:
df.iloc[:,2]

0     2
1     6
2    10
Name: C, dtype: int64